OnlineApp.Core/OnlineApp.MVC/Controllers/ComponentsController.cs
using OnlineApp.Core.Entities;
using OnlineApp.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineApp.Mvc.Filter;

namespace OnlineApp.Mvc.Controllers
{

    public class ComponentsController : Controller
    {
        // GET: Products/Create
        public ActionResult Create()
        {
            OnlineClient lc = new OnlineClient();
            ViewBag.listManufacturers = lc.GetManufacturersIdName().Select
                                      (x => new SelectListItem
                                      {
                                          Value = x.ID.ToString(),
                                          Text = x.NAME
                                      });
            ViewBag.listTypes = lc.GetTypeIdNameMVCModel().Select
                                      (x => new SelectListItem
                                      {
                                          Value = x.NAME,
                                          Text = x.NAME
                                      });
            return View();
        }



        // POST: Products/Create
        [HttpPost]
        public ActionResult Create(Components components)
        {
            OnlineClient lc = new OnlineClient();
            lc.CreateComponent(components);
            return RedirectToAction("AdminIndex", "ComponentsWithManufacturers");
        }

        // GET: Products/Delete
        public ActionResult Delete(int id)
        {
            OnlineClient lc = new OnlineClient();
            lc.DeleteComponent(id);
            return RedirectToAction("AdminIndex", "ComponentsWithManufacturers");
        }
        // GET: Products/Edit
        [HttpGet]
        public ActionResult Edit(int id)
        {
            OnlineClient lc = new OnlineClient();
            Components components = new Components();
            components = lc.GetComponent(id);
            ViewBag.listManufacturers = lc.GetManufacturersIdName().Select
                                                       (x => new SelectListItem
                                                       {
                                                           Value = x.ID.ToString(),
                                                           Text = x.NAME
                                                       });
            ViewBag.listEditions = lc.GetTypeIdNameMVCModel().Select
                                                      (x => new SelectListItem
                                                      {
                                                          Value = x.NAME,
                                                          Text = x.NAME
                                                      });
            return View("Edit", components);
        }
        // POST: Products/Edit
        [HttpPost]
        public ActionResult Edit(Components components)
        {
            OnlineClient pc = new OnlineClient();
            pc.EditComponent(components);
            return RedirectToAction("AdminIndex", "ComponentsWithManufacturers");
        }
        public ActionResult Details(int id)
        {
            OnlineClient lc = new OnlineClient();
            //Components components = new Components();
            Components components = lc.GetComponent(id);
            //ViewBag.listManufacturers = lc.GetManufacturersIdName().Select
            //                                           (x => new SelectListItem
            //                                           {
            //                                               Value = x.ID.ToString(),
            //                                               Text = x.NAME
            //                                           });
            //ViewBag.listEditions = lc.GetTypeIdNameMVCModel().Select
            //                                          (x => new SelectListItem
            //                                          {
            //                                              Value = x.NAME,
            //                                              Text = x.NAME
            //                                          });
            //lc.
            return RedirectToAction("Index", "Orders");
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

OnlineApp.Core/OnlineApp.MVC/Controllers/OrdersController.cs
using OnlineApp.Core.Entities;
using OnlineApp.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineApp.Mvc.Controllers
{
    public class OrdersController : Controller
    {
        //public ActionResult Create()
        //{
        //    OnlineClient lc = new OnlineClient();
        //    //ViewBag.listCompanies = lc.GetCompaniesIdName().Select
        //    //                          (x => new SelectListItem
        //    //                          {
        //    //                              Value = x.ID.ToString(),
        //    //                              Text = x.NAME
        //    //                          });
        //    ViewBag.listTypes = lc.GetTypeIdNameMVCModel().Select
        //                              (x => new SelectListItem
        //                              {
        //                                  Value = x.NAME,
        //                                  Text = x.NAME
        //                              });
        //    return View();
        //}
        //[HttpPost]
        public ActionResult AddToCart(int componentId)
        {
            OnlineClient lc = new OnlineClient();
            Order order = new Order();
            order.Component_Id = componentId;
            order.UserId = Convert.ToInt32(Session["userid"].ToString());
            lc.AddToCart(order);
            return RedirectToAction("Index");
            //return View();
        }
        public ActionResult Index()
        {
            OnlineClient lc = new OnlineClient();
            List<Order> lstorders = new List<Order>();
            if (Session["userid"] != null)
            {
                var userId = Convert.ToInt32(Session["userid"].ToString());
                lstorders = lc.GetAllOrders(userId).ToList();
            }
            return View(lstorders);
        }
    }
}

OnlineApp.Core/OnlineApp.MVC/Views/Orders/Index.cshtml
@model IEnumerable<OnlineApp.Core.Entities.Order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Continue Shopping", "ComponentsWithManufacturers","ComponentsWithMAnufacturers")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Order_ComponentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order_Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order_Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order_Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.total)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Order_ComponentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order_Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order_Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order_Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Order_Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Order_Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Order_Id })
            </td>*@
        </tr>
    }

</table>

Total Cart Amount : @Model.Select(a => a.total).Sum()
<a onclick="return confirm('Are you sure to place order ?')" href="@Url.Action("Index","Components" @*, new { id = item.ComponentsWithManufacturer_Id }*@)"><span class="glyphicon glyphicon-shopping-cart"></span>Order Now</a>