OnlineApp.Core/OnlineApp.MVC/Controllers/ComponentsWithManufacturersController.cs
using OnlineApp.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineApp.Mvc.Filter;

namespace OnlineApp.Mvc.Controllers
{
    public class ComponentsWithManufacturersController : Controller
    {

        public ActionResult ComponentsWithManufacturers()
        {
            OnlineClient bwu = new OnlineClient();
            ViewBag.listComponentsWithManufacturers = bwu.GetComponentsWithManufacturers();
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Login");
        }
        //[AllowAnonymous]
        public ActionResult AdminIndex()
        {
            OnlineClient bwu = new OnlineClient();
            ViewBag.listComponentsWithManufacturers = bwu.GetComponentsWithManufacturers();
            return View();
        }

    }
}

OnlineApp.Core/OnlineApp.MVC/Controllers/ManufacturersController.cs
using OnlineApp.Core.Entities;
using OnlineApp.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineApp.Mvc.Controllers
{
    public class ManufacturersController : Controller
    {
        public ActionResult Index()
        {
            OnlineClient lc = new OnlineClient();
            ViewBag.listManufacturers = lc.GetAllManufacturers();
            return View();
        }

        public ActionResult Create()
        {
            OnlineClient lc = new OnlineClient();
            ViewBag.listAuthorizationStatus = lc.GetAuthorizationStatusIdNameMVCModel().Select
            (x => new SelectListItem
            {
                Value = x.NAME,
                Text = x.NAME
            });
               return View("Create");
        }

        // POST: Companies/Create
        [HttpPost]
        public ActionResult Create(Manufacturer manufacturer)
        {
            OnlineClient lc = new OnlineClient();
            lc.CreateManufacturer(manufacturer);
            return RedirectToAction("Index", "Manufacturers");
        }

        public ActionResult Delete(int id)
        {
            OnlineClient lc = new OnlineClient();
            lc.DeleteManufacturer(id);
            return RedirectToAction("Index", "Manufacturers");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            OnlineClient lc = new OnlineClient();
            Manufacturer manufacturer = new Manufacturer();
            ViewBag.listAuthorizationStatus = lc.GetAuthorizationStatusIdNameMVCModel().Select
            (x => new SelectListItem
            {
                Value = x.NAME,
                Text = x.NAME
            });
            manufacturer = lc.GetManufacturer(id);

            return View("Edit", manufacturer);
        }

        [HttpPost]
        public ActionResult Edit(Manufacturer manufacturer)
        {
            OnlineClient pc = new OnlineClient();
            pc.EditMAnufacturer(manufacturer);
            return RedirectToAction("Index", "Manufacturers");
        }
    }
}

OnlineApp.Core/OnlineApp.MVC/Views/Manufacturers/Create.cshtml
@model OnlineApp.Core.Entities.Manufacturer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manufacturer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAuthorized, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAuthorized, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsAuthorized, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineApp.Core/OnlineApp.MVC/Views/Manufacturers/Delete.cshtml
@model OnlineApp.Core.Entities.Manufacturer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Manufacturer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAuthorized)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAuthorized)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineApp.Core/OnlineApp.MVC/Views/Manufacturers/Edit.cshtml
@model OnlineApp.Core.Entities.Manufacturer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manufacturer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Manufacturer_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAuthorized, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAuthorized, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsAuthorized, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineApp.Core/OnlineApp.MVC/Views/Manufacturers/Index.cshtml
@{ ViewBag.Title = "Manufacturers";
    Layout = "~/Views/Shared/_Layout.cshtml"; }



<h4> All Manufacturers</h4>



<p>
    <button type="button"  onclick="location.href='@Url.Action("AdminIndex", "ComponentsWithManufacturers")';"><span class="glyphicon glyphicon-list-alt"></span> Component list </button>
    <button type="button"  onclick="location.href='@Url.Action("Create", "Manufacturers")';"><span class="glyphicon glyphicon-plus"></span> Create a Manufacturer</button>
</p>



<table class="table">
    <tr>
        <th>
            Manufacturer ID
        </th>
        <th>
            Manufacturer Name
        </th>

        <th>
            Components Availability Status
        </th>
        <th>
            Action
        </th>
    </tr>



    @foreach (var item in ViewBag.listManufacturers)
    {
<tr>
    <td>
        @item.Manufacturer_Id
    </td>
    <td>
        @item.Manufacturer_Name



    </td>

    <td>



        @if (item.IsAuthorized == "Y")
        {



<p><span class="glyphicon glyphicon-ok" style="color:lime"></span></p>}



        @if (item.IsAuthorized == "N")
        {
<p><span class="glyphicon glyphicon-remove" style="color:deeppink"></span></p>}



    </td>



    <td>
        <a  onclick="return confirm('Are you Sure ?')" href="@Url.Action("Delete","Manufacturers" , new { id = item.Manufacturer_Id })"><span class="glyphicon glyphicon-trash"></span> Delete Manufacturer</a>
        <a  href="@Url.Action("Edit","Manufacturers" , new { id = item.Manufacturer_Id })"><span class="glyphicon glyphicon-scissors"></span> Edit Manufacturer</a>
    </td>
</tr>
}
</table>